export const FETCH_WORD_IMAGES = "FETCH_WORD_IMAGES"
export const FETCH_WORD_IMAGES_START = "FETCH_WORD_IMAGES_START"
export const FETCH_WORD_IMAGES_SUCCESS = "FETCH_WORD_IMAGES_SUCCESS"
export const FETCH_WORD_IMAGES_FAIL = "FETCH_WORD_IMAGES_FAIL"

export const FETCH_WORD_DEFINITION = "FETCH_WORD_DEFINITION"
export const FETCH_WORD_DEFINITION_START = "FETCH_WORD_DEFINITION_START"
export const FETCH_WORD_DEFINITION_SUCCESS = "FETCH_WORD_DEFINITION_SUCCESS"
export const FETCH_WORD_DEFINITION_FAIL = "FETCH_WORD_DEFINITION_FAIL"

export const ADD_WORD_TO_DICTIONARY = "ADD_WORD_TO_DICTIONARY"
export const ADD_WORD_TO_DICTIONARY_START = "ADD_WORD_TO_DICTIONARY_START"
export const ADD_WORD_TO_DICTIONARY_SUCCESS = "ADD_WORD_TO_DICTIONARY_SUCCESS"
export const ADD_WORD_TO_DICTIONARY_FAIL = "ADD_WORD_TO_DICTIONARY_FAIL"

export const FETCH_DICTIONARY_WORDS = "FETCH_DICTIONARY_WORDS"
export const FETCH_DICTIONARY_WORDS_START = "FETCH_DICTIONARY_WORDS_START"
export const FETCH_DICTIONARY_WORDS_SUCCESS = "FETCH_DICTIONARY_WORDS_SUCCESS"
export const FETCH_DICTIONARY_WORDS_FAIL = "FETCH_DICTIONARY_WORDS_FAIL"
